                                                                                                                                                                                                                                                                
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (1, '.NET Bot Black Sweatshirt', '.NET Bot Black Sweatshirt', 19.50, 'http://catalogbaseurltobereplaced/images/products/1.png', 2, 2);                     
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (2, '.NET Black & White Mug', '.NET Black & White Mug', 8.50, 'http://catalogbaseurltobereplaced/images/products/2.png', 1, 2);                            
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (3, 'Prism White T-Shirt', 'Prism White T-Shirt', 12.00, 'http://catalogbaseurltobereplaced/images/products/3.png', 2, 5);                                 
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (4, '.NET Foundation Sweatshirt', '.NET Foundation Sweatshirt', 12.00, 'http://catalogbaseurltobereplaced/images/products/4.png', 2, 2);                   
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (5, 'Roslyn Red Sheet', 'Roslyn Red Sheet', 8.50, 'http://catalogbaseurltobereplaced/images/products/5.png', 3, 5);                                        
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (6, '.NET Blue Sweatshirt', '.NET Blue Sweatshirt', 12.00, 'http://catalogbaseurltobereplaced/images/products/6.png', 2, 2);                               
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (7, 'Roslyn Red T-Shirt', 'Roslyn Red T-Shirt', 12.00, 'http://catalogbaseurltobereplaced/images/products/7.png', 2, 5);                                   
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (8, 'Kudu Purple Sweatshirt', 'Kudu Purple Sweatshirt', 8.50, 'http://catalogbaseurltobereplaced/images/products/8.png', 2, 5);                            
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (9, 'Cup<T> White Mug', 'Cup<T> White Mug', 12.00, 'http://catalogbaseurltobereplaced/images/products/9.png', 1, 5);                                       
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (10, '.NET Foundation Sheet', '.NET Foundation Sheet', 12.00, 'http://catalogbaseurltobereplaced/images/products/10.png', 3, 2);                           
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (11, 'Cup<T> Sheet', 'Cup<T> Sheet', 8.50, 'http://catalogbaseurltobereplaced/images/products/11.png', 3, 2);                                              
INSERT INTO Catalog (Id, Name, Description, Price, PictureUri, CatalogTypeId, CatalogBrandId) VALUES (12, 'Prism White TShirt', 'Prism White TShirt', 12.00, 'http://catalogbaseurltobereplaced/images/products/12.png', 2, 5);                                 
